# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 159c902fa4486103d0556a7ad9b55580f40cb86889c9af07ed953204a0c3de50e5c5fffac56829b906d1009144da0d1c8cebcf4fdf8cc1f8d6fc2b915c9284be

test:
  secret_key_base: 8db4c22d820a783516c65e7cafef0f6003d24285d80759d061b3c68fcee48fa60c44108847029a246f199abf33873ef9e590f4b5a11a653da5620c99cf60981a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
